include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_print: false
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_void_async: true
    await_only_futures: true
    empty_constructor_bodies: true
    prefer_const_constructors: true
    prefer_constructors_over_static_methods: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    use_decorated_box: true
    void_checks: true

    analyzer:
      language:
        strict-casts: true
